inherit_from: .rubocop_upstream.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "hubstep.gemspec"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/LineLength:
  Max: 115

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 17

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IfUnlessModifier:
  Enabled: false

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
